// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace TronClass.Interop
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "tronclass_core";





        /// <summary>
        ///  Start the core. `cb` is invoked (from runtime worker threads) with UTF-8 JSON event
        ///  bytes that are valid only for the duration of each call. Returns an opaque handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "core_init", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* core_init(delegate* unmanaged[Cdecl]<byte*, nuint, void> cb);

        /// <summary>
        ///  Send one UTF-8 JSON command. Returns immediately; results arrive via the callback.
        ///
        ///  # Safety
        ///  `handle` must be a live pointer from `core_init`; `json_ptr`/`json_len` must describe
        ///  a valid byte range for the duration of the call.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "core_send", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void core_send(void* handle, byte* json_ptr, nuint json_len);

        /// <summary>
        ///  Free the handle and shut down its runtime. The handle must not be used afterwards.
        ///
        ///  # Safety
        ///  `handle` must be a live pointer from `core_init` and must not be used again.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "core_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void core_free(void* handle);


    }



}
