// Generates the C# P/Invoke bindings from the extern "C" surface in src/lib.rs.
// One narrow ABI (init/send/free + one callback); the evolving command/event schema
// rides as JSON, so this file stays tiny and stable.
// Normal cargo build NEVER mutates the tracked ui/Interop/NativeMethods.g.cs.
// It generates into OUT_DIR and verifies bytes; mismatch fails with an explicit update command.
fn main() {
    // ── rerun inputs ──
    // Explicit directives are intentionally conservative: any source/config/lock change
    // must trigger re-verification so a stale binding is never silently reused.
    // Cargo also fingerprints build-dependencies (csbindgen) via Cargo.lock/Cargo.toml,
    // but we declare inputs explicitly for clarity and for cases where lock is absent.
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=Cargo.toml");
    // Cargo.lock may be absent in some publish contexts; cargo treats a missing path as
    // "watch for creation", which is the desired conservative behavior.
    println!("cargo:rerun-if-changed=Cargo.lock");
    // The entire src tree influences the FFI surface; watching the directory covers all
    // Rust sources, assets that could affect codegen, and future files without enumeration drift.
    println!("cargo:rerun-if-changed=src");
    // If maintainers use an explicit update env to control generation, changes must rerun.
    println!("cargo:rerun-if-env-changed=TRONCLASS_UPDATE_BINDINGS");
    println!("cargo:rerun-if-env-changed=TRONCLASS_BINDINGS_UPDATE");

    // ── normal build: verify only, never touch tracked file ──
    let out_dir = std::env::var("OUT_DIR")
        .unwrap_or_else(|_| panic!("OUT_DIR not set — refusing source-tree fallback temp (would pollute repo and could be left behind on panic). Run via cargo build."));

    let tracked = "../ui/Interop/NativeMethods.g.cs";
    let tmp = std::path::Path::new(&out_dir).join("NativeMethods.g.cs.tmp");

    // Generate directly into OUT_DIR (ignored, never in source tree). Any panic leaves
    // at most an ignored file under target/, never a half-written tracked file.
    csbindgen::Builder::default()
        .input_extern_file("src/lib.rs")
        .csharp_dll_name("tronclass_core")
        .csharp_namespace("TronClass.Interop")
        .csharp_class_name("NativeMethods")
        .generate_csharp_file(&tmp)
        .expect("csbindgen: generate C# bindings");

    let new_bytes = std::fs::read(&tmp).expect("read OUT_DIR tmp bindings");
    // Clean the OUT_DIR temp promptly; even if we keep it, it stays under ignored target/.
    // Remove explicitly so repeated builds don't accumulate, but failure to remove is non-fatal.
    let _ = std::fs::remove_file(&tmp);

    let old_bytes = std::fs::read(tracked).unwrap_or_else(|e| {
        panic!(
            "tracked bindings missing at {} ({}). Generate it with: pwsh ./tools/update-bindings.ps1",
            tracked, e
        )
    });

    if new_bytes != old_bytes {
        // Never truncate or replace the tracked file in normal build — fail closed.
        // Diagnostics are bounded and do not dump file contents.
        let new_hash = {
            use std::collections::hash_map::DefaultHasher;
            use std::hash::{Hash, Hasher};
            let mut h = DefaultHasher::new();
            new_bytes.hash(&mut h);
            format!("{:016x}", h.finish())
        };
        panic!(
            "bindings mismatch: generated bytes differ from committed {} ({} bytes vs {} bytes, new hash {}). Refusing to mutate tracked file in normal build. Run: pwsh ./tools/update-bindings.ps1",
            tracked,
            new_bytes.len(),
            old_bytes.len(),
            new_hash
        );
    }
}
